# Generated by Django 4.2.6 on 2023-10-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0003_projects_github_projects_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='github',
            field=models.URLField(default=None, max_length=255, null=True),
        ),
    ]
