# Generated by Django 4.2.6 on 2023-10-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0004_alter_projects_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='github',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
