# Generated by Django 4.2.6 on 2023-10-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0005_alter_projects_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='professional',
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('professional', 'Professional'), ('personal', 'Personal')], default='personal', max_length=12),
        ),
    ]
