# Generated by Django 4.2.6 on 2023-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0007_alter_projects_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default='qweqw', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='projects',
            index_together={('id', 'slug')},
        ),
    ]
