# Generated by Django 4.2.6 on 2023-10-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0008_alter_projects_options_projects_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='details',
            field=models.TextField(),
        ),
    ]
